source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'OAuth2_Example', :exclusive => true do
  pod "OAuth2", :path => "../"
end

target 'OAuth2_Tests', :exclusive => true do
  pod "OAuth2", :path => "../"

  
end
